# Generated by Django 4.2.4 on 2023-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publish'], name='blog_articl_publish_61496a_idx'),
        ),
    ]
