# Generated by Django 4.2.4 on 2023-08-12 15:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر ', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('active_comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
