# Generated by Django 4.2.4 on 2023-08-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
