# Generated by Django 4.2.4 on 2023-08-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ipaddress_articlehit_article_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آیپی آدرس', 'verbose_name_plural': 'آیپی آدرس ها'},
        ),
    ]
