# Generated by Django 4.2.4 on 2023-08-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_ipaddress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.DeleteModel(
            name='ArticleHit',
        ),
    ]
